version: '3'

services:

  api-gateway:
    restart: unless-stopped
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file: ./api-gateway/.env
    ports:
      - 3000:3000

  mongo:
    image: mongo
    ports:
      - 27012:27017
    volumes:
      - ./data:/data/db

  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CLEAN_NEST_MONGO_CONNECTION_STRING=mongodb://mongo:27017/db_account
      - JWT_SECRET=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4NjE0NjU0NywiaWF0IjoxNjg2MTQ2NTQ3fQ.lERf9qhXEOBoyZO0_TlhmovhE-1y2LO3tziZZzs4pQU
      - JWT_EXPIRED=3d
    ports:
      - 3001:3001
    links:
      - api-gateway
    depends_on:
      - mongo
      - api-gateway
